### Listar todas las categorias
GET http://127.0.0.1:4000/api/categoria
Accept: application/json

### Guardar categoria
POST http://127.0.0.1:4000/api/categoria
Accept: application/json
Content-Type: application/json

{
    "nombre" : "prueba",
    "detalle" : "ejejejejej"
}

### Mostrar Categoria
GET http://127.0.0.1:4000/api/categoria/3
Accept: application/json

### Modificar categoria
PUT http://127.0.0.1:4000/api/categoria/3
Accept: application/json
Content-Type: application/json

{
    "nombre" : "Juego",
    "detalle" : "PES 2023 modificado"
}

### Eliminar categoria
DELETE http://127.0.0.1:4000/api/categoria/7
Accept: application/json